MapColonies/raster-shared

- package-lock.json
- package.json
> chore: use standard-version

- .versionrc.json
- CHANGELOG.md
- package-lock.json
- package.json
> chore: typedoc

- package.json
> chore: remove strict node engine

- src/constants/core/constants.ts
- src/constants/ingestion/constants.ts
- src/schemas/core/job.schema.ts
- src/schemas/core/task.schema.ts
- src/schemas/export/export.schema.ts
- src/schemas/export/job.schema.ts
- src/schemas/ingestion/metadata.schema.ts
- src/schemas/ingestion/polygonParts.schema.ts
- src/types/export/export.type.ts
- src/types/ingestion/types.ts
> fix: tighten validations, modify export schemas

- src/schemas/ingestion/polygonParts.schema.ts
- src/types/ingestion/types.ts
> feat: add polygonPartsPayloadSchema for ingestion validation

- src/openapi/core/geojson.yaml
> feat: add GeoJSON openapi definitions and schemas

- package-lock.json
- package.json
- src/schemas/export/export.schema.ts
- src/types/export/export.type.ts
> fix: Integrate export management

- src/schemas/export/export.schema.ts
| Bug fix         |  ✖                                                                        |
| Deprecations    | ✔                                                                        | …
> feat: remove metadataUri

- src/schemas/core/job.schema.ts
- src/schemas/export/export.schema.ts
> fix: job schema, cleanupDataSchema

- src/schemas/export/export.schema.ts
- src/schemas/export/job.schema.ts
> feat: Add job tracker to export params

- src/schemas/export/job.schema.ts
- src/utils/index.ts
- src/utils/utils.ts
> feat: add entityName to export params

- src/schemas/export/export.schema.ts
- src/schemas/export/task.schema.ts
- src/types/export/export.type.ts
- src/types/export/job.type.ts
> feat: add failure handling in export

- src/types/export/export.type.ts
> refactor: update LinksDefinition type to use linksSchema and add FileNamesTemplates type

- src/schemas/export/task.schema.ts
> fix: make gpkgModified and gpkgUploadedToS3 required in exportFinalizeTaskParamsSchema

- src/index.ts
| Deprecations    |✖                                                                        |
| Chore            | ✖ …
> refactor: update exports in index.ts to prioritize utils for better module resolution

- src/schemas/export/export.schema.ts
- src/types/export/export.type.ts
> feat: enhance callback export response schema to include IN_PROGRESS status

- src/openapi/export/export.yaml
- src/schemas/export/task.schema.ts
> feat: add OpenAPI export definitions for GeoJSON features and properties

- src/schemas/export/export.schema.ts
> fix: use zod coerce date to validate date and string date

- src/types/core/metadata.ts
| Breaking change | ✔                                                                        | …
> feat: add productStatus

- src/types/core/metadata.ts
Reverts MapColonies/raster-shared#69
> Revert "feat: add productStatus"

- src/types/core/metadata.ts
> feat: add product status

- src/schemas/core/geo.schema.ts
- src/schemas/export/export.schema.ts
- src/utils/geo.ts
| Breaking change | ✔                                                                        | …
> feat!: geojson schemas and rename

- src/schemas/core/geo.schema.ts
> refactor: add custom error message for polygon coordinates first and last value validation

- src/schemas/export/export.schema.ts
> feat: add metadataURI and jsonFileData to links and callbackExportData schemas

- src/constants/export/constants.ts
> fix: exportFinalizeType add as const

- package-lock.json
- package.json
> build: moved standard-version to devDep as it should be

- .vscode/settings.json
- src/constants/ingestion/constants.ts
- src/schemas/ingestion/index.ts
- src/schemas/ingestion/ingestionRequest.schema.ts
- src/schemas/ingestion/inputFiles.schema.ts
- src/schemas/ingestion/polygonParts.schema.ts
- src/schemas/ingestion/shapefile.schema.ts
- src/types/ingestion/types.ts
| Breaking change | ✔                                                                        |
Further  information:
1. Changing Ingestion-trigger request to support shapeFilePath instead of raw partsData .
2. Chnage partsData to featureCollerction to feat geojson convention.
3. shapeFile path validation
> feat: add shapefile validation and update schemas for new ingestion processing flow(MAPCO-8119)
